version: "3.1"

services:
  beer-kit:
    depends_on:
      - beer-service
    build: "./beer-kit"
    environment:
      - PUBLIC_API_URL=http://localhost:9080/beers
      - API_URL=http://beer-service:8080/beers
    ports:
      - "3000:3000"
  beer-service:
    depends_on:
      - beer-db
    build: "./beer-service"
    ports:
      - "9080:8080"
    environment:
      - MONGODB_URI=mongodb://beer-db:27017
  beer-db:
    image: mongo:latest
    volumes:
      - type: bind
        source: "./data"
        target: "/data/db"
